name: multi_level_pie
description: "Create beautiful multi-level-pie chart with detailed information"
version: 0.0.1
homepage: https://github.com/gabbygreat/multi_level_pie

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
